name: Full Unoptimized Build
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 2 * * *"
jobs:
  full:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: gradle/gradle-build-action@v2
      - run: ./gradlew build --no-build-cache --no-configuraton-cache
