name: Update Dependencies
on: [push]
jobs:
  update-gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.0.2
      - run: gradle wrapper --write-locks
      - run: ./gradlew --version
      - run: ./gradlew dependencies --write-locks
      - uses: peter-evans/create-pull-request@v5
