name: Update Dependencies
on:
  push:
    branches: ["ccushing/auto-updates"]
  schedule:
    - cron: "0 4 * * 4"
jobs:
  update-java:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current
      - run: gradle wrapper --write-locks
      - run: ./gradlew --version
      - run: ./gradlew dependencies --write-locks
      - run: ./gradlew build --no-build-cache
      - uses: peter-evans/create-pull-request@v5
        with:
          title: "chore: Update Java Dependencies"
